# Generated by Django 3.2.6 on 2021-10-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_rename_question_poll_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='Name',
            field=models.CharField(max_length=20),
        ),
    ]
